<?php

/**
 * @file
 * Module file used for theming the Tender content type.
 */

declare(strict_types = 1);

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_ENTITY_TYPE_view_alter().
 */
function oe_theme_content_tender_node_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  // Run only on tender content type.
  if ($entity->bundle() !== 'oe_tender') {
    return;
  }

  // Field labels are different in frontend and backend.
  // Here we override them, per view mode.
  if ($build['#view_mode'] === 'full') {
    $label_overrides = [
      'body' => t('Description'),
      'oe_departments' => t('Departments'),
    ];

    foreach ($label_overrides as $name => $label_override) {
      if (!$entity->get($name)->isEmpty() && isset($build[$name]['#title'])) {
        $build[$name]['#title'] = $label_override;
      }
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function oe_theme_content_tender_preprocess_field(&$variables, $hook) {
  if ($variables['field_name'] == 'oe_tender_deadlines') {
    $now = new DateTime('now');
    foreach(array_keys($variables['items']) as $delta) {
      $date = new DateTime($variables['element']['#items']->getValue()[$delta]['value']);
      if ($date < $now) {
        $variables['items'][$delta]['attributes']->setAttribute('class', 'ecl-u-type-strike');
      }
    }
  }
}
